electrostore/urls.py
from django.contrib import admin
from django.urls import path, include
from myapp import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('user/login/',views.uslogin,name='uslogin'),
    path('logout/',views.uslogout,name='uslogout'),
    path('accounts/profile/',views.authemail,name='authemail'), #CUSTOM
    path('myapp/',include('myapp.urls')),
    path('auth/',include('social_django.urls',namespace='social')),
    path('paypal/',include('paypal.standard.ipn.urls')),

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)+static(settings.STATIC_URL,document_root=settings.STATIC_DIR)

myapp/urls.py
from django.urls import path
from myapp import views

app_name='myapp'
 
urlpatterns = [
    path('usregister/',views.usregister,name='usregister'),
    path('dashboard/',views.dashboard,name='dashboard'),
    path('uservalid/',views.uservalid,name='uservalid'),
    path('about/',views.about,name='about'),
    path('showproducts/',views.showproducts,name='showproducts'),
    path('singleproduct/',views.singleproduct,name='singleproduct'),
    path('mail/',views.usermail,name='mail'),
    path('base/',views.base,name='base'),
    path('cart/',views.addcart,name='cart'),
    path('removecart/',views.removeCart,name='removecart'),
    path('grandTotal/',views.grandTotal,name='grandTotal'),
    path('sendMail/',views.sendMail,name='sendMail'),
    path('success_payment/',views.success_payment, name='success_payment'),
    path('get_order/',views.get_order, name='get_order'),
    path('orders/',views.orders, name='orders'),
    path('pending_orders/',views.pending_orders, name='pending_orders'),
    path('profile/',views.profile, name='profile'),
    path('change_profile/',views.change_profile, name='change_profile'),
    path('singleorder/',views.singleorder, name='singleorder'),
    path('change_password/',views.change_password, name='change_password'),
    path('order_detail/',views.order_detail, name='order_detail'),
]

templates/cart.html
{% extends "dashboard.html" %}
{% load staticfiles %}
{% block content %}
{% if user.is_authenticated %}
<style>
    .spinnerouter{
        background:rgb(0,0,0,0.5);position:fixed;width: 100%;height: 100%;z-index:99999;
        top:0px;display: none;}
    .loader {
        border: 16px solid #f3f3f3; /* Light grey */
        border-top: 16px solid rgb(60, 67, 164); /* Blue */
        border-radius: 50%;
        width: 120px;
        height: 120px;
        animation: spin 1s linear infinite;
        position: absolute;
        left:45%;
        top:45%;
        z-index:999999;
    }
    .spinner-border{
        height:25px;width:25px;border:5px solid white;border-top:5px solid #f0ad4e;
        animation: spin 1s linear infinite;border-radius:50%;margin:auto;
    }
    @keyframes spin {
        0% { transform: rotate(0deg); }
        100% { transform: rotate(360deg); }
    }
    table,td{
    color:black !important;
   }


</style>
<div class="spinnerouter">
    <div class="loader">

    </div>
</div>
<div class='container' style="padding:10px;">
    <div class='row'>
        <div class='col-md-12'>
            {% if messages %}
            {% for i in messages %}
                <div class="alert alert-{{i.tags}} status">{{i}}</div>
            {% endfor %}
            {% endif %}
        </div>
        {% if cart_size is 0 %}
        <div class='col-md-12' style='padding:20px;' id='empty'>
            <h2>❌ Your Shopping Cart is Empty</h2>
        </div>
        {% else %}
        
            <div class='col-md-8'>
                <h2>My Cart(<span id='csize'>{{cart_size}}</span> )</h2>
                <hr/>
                <ul class='list-group'>
                    {% for i in cart %}
                    <li class='list-group-item c-{{i.id}}' style='box-shadow:0px 0px 10px black;'>
                        <div class='row'>
                            <div class='col-md-3' style='text-align:center;font-size:30px;'>
                                <span>
                                    <img src="/media/{{i.photo}}" style='border-radius:50%;margin:10px;' height='70' width='70' class='rounded-circle'>
                                    <div class='form-group'>
                                        <div class='row'>
                                            <div class='col-md-3 col-sm-3 col-3'>
                                                <span onclick="addNum('{{i.id}}','add')">
                                                    <i class="fas fa-plus-circle text-success"></i>
                                                </span>
                                            </div>
                                            <div class='col-md-6 col-sm-6 col-6'>
                                                <input type="number" id="num" value='{{i.quantity}}' class='form-control num{{i.id}}'>
                                            </div>
                                            <div class='col-md-3 col-sm-3 col-3'>
                                                <span onclick="addNum('{{i.id}}','sub')">              
                                                    <i class="fas fa-minus-circle text-danger"></i>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                </span>
                            </div>
                            <div class='col-md-9'>
                                <span class='text-danger font-weight-bold'>
                                    <strong>{{i.product_name}}</strong><br/>
                                    |{{i.product_cat}} | {{i.brand}}
                                </span>
                                <h4 STYLE='margin-top:20px;'><strong class='text-success cartsaleprice{{i.id}}'>&#8377;{{i.price}}</strong> <del style='font-size:12px;' class='cartprice{{i.id}}'> &#8377; {{i.market}}</del>
                                    <span style='color:green;font-family:arial'>You save {{i.offer}}%</span>
                                </h4>
                            </div>
                        </div> 
                        <hr/>
                    </li>           
                    {% endfor %}
                </ul>    
            </div>
            <div class='col-md-4'>
                {% if cart_size is not  0 %}
                <h2>Price Details</h2>
                <hr/>
                <div style='border:1px solid gray;padding:10px;border-radius:5px;'>
                    <table class='table'>
                        <tbody>
                            <tr>
                                <td id='itotal'>ITEM TOTAL</td>
                                <td id='total'></td>
                            </tr>
                            <tr style='border-bottom:1px dotted gray;'>
                                <td>DELIVERY CHARGES</td>
                                <td>FREE</td>
                            </tr>
                            <tr>
                                <td><strong>GRAND TOTAL</strong></td>
                                <td id='grand'></td>
                            </tr>
                            
                        </tbody>
                    </table>
                    <hr/>
                    <div style='padding:10px; display:none;' id='delivery_address'>
                        <h4>Enter Delivery Details</h4>
                        <hr/>
                        
                            <div class='form-group'>
                                <input type="text" class='form-control' placeholder='Enter Name' id='dname' required>
                            </div>
                            <div class='form-group'>
                                <!-- <label for="" id='res'></label> -->
                                <input type="email" class='form-control' placeholder='Enter Email Address' id='demail' required>
                            </div>
                            <!-- <div class='form-group' style='display:none;'>
                                <input type="number" class='form-control' placeholder='Enter OTP Here' id='id_enter_otp'>
                            </div> -->
                            <div class='form-group'>
                                <input type="number" class='form-control' placeholder='Enter Mobile Number' id='dnumber' required>
                            </div>
                            <div class='form-group'>
                                <textarea name="daddress" id="daddress" class='form-control' placeholder='Enter Full Address' required></textarea>
                            </div>
                            <div class='form-group'>
                                <input type="hidden" id='grandtotal'>
                                <input type="hidden" id='items' value='{{cids}}'>
                                <button class='btn btn-success btn-block' id='ptp'>Proceed To Pay</button>
                            </div>
                        

                    </div>
                    <button class='btn btn-warning btn-block' id='ptb'><i class='fas fa-shopping-cart'></i> Proceed To Buy</button>
                </div>
                {% endif %}
            </div>
        
        {% endif %}
    </div>
</div>
<script>
function addNum(id,action){
    $('.spinnerouter').show();
    let v = $('.num'+id).val();
    let updateQuant = 0;
    if(action=='add'){
        updateQuant = parseInt(v)+1;    
    }else{
        updateQuant = parseInt(v)-1;    
    }
    setTimeout(function(){
        $.ajax({
            url:'{% url "myapp:cart" %}',
            type:'get',
            data:{q:updateQuant,id:id},
            success:function(data){
                $('.num'+id).val(data.quantity);
                $('.cartsaleprice'+id).html(data.sale_price*data.quantity);
                $('.cartprice'+id).html(data.price*data.quantity);
                $('.spinnerouter').hide();
                $('#csize').html(data.cart_size);
                grandTotal()

                // #Remove Items
                if(data.quantity==0){
                $.ajax({
                    url:'{% url "myapp:removecart" %}',
                    data:{removeid:id},
                    success:function(data){
                        $('.c-'+id).hide();
                        $('.status').html(data.msz);
                        $('#csize').html(data.cart_size);
                    }
                });
            }              
            }
        });
    });
}
</script>

<script>
    let email;
function grandTotal(){
    $.ajax({
        url:'{% url "myapp:grandTotal" %}',
        success:function(data){
            $('#itotal').html('ITEM TOTAL ('+data.quantity+')');
            $('#total').html('&#8377;'+data.grand_total);
            $('#grand').html('&#8377;'+data.grand_total);
            $('#demail').val(data.email)
            $('#dname').val(data.name)
            $('#daddress').val(data.address)
            $('#grandtotal').val(data.grand_total);
            $('#ptp').html('Proceed To Pay &#8377;'+ data.grand_total)
        }
    });
}
$(function(){
    grandTotal();
})
</script>
<script>
$('#ptb').click(function(){
    $(this).html('<div class="spinner-border"></div>');
    setTimeout(function(){
        $('#delivery_address').slideDown(1000);
        $('#ptb').hide();
    },1500);
});
</script>

<!-- VERIFICATION EMAIL --> 
<script>
var arr = [];
$('#dnu').focus(function(){
    var name = $('#dname').val();
    var email = $('#demail').val();
    $.ajax({
    url:'{% url "myapp:sendMail"%}',
    data:{name:name,email:email},
    success:function(data){
        arr = data.split('@');
        $('#res').html(arr[0]).addClass('text-success');
        $('#id_enter_OTP').show();
    }
    });
});
</script>

<script>
$('#ptp').click(function(){
    let dname = $('#dname').val();
    let demail = $('#demail').val();
    let daddr =$('#daddress').val();
    let dcon = $('#dnumber').val();
    let amount = $('#grandtotal').val();
    let it = $('#items').val();
    $.ajax({
        url:'{% url "myapp:get_order"%}',
        type:'get',
        data:{'grandtotal':amount,'dname':dname,'demail':demail,'daddress':daddr,'dnumber':dcon,'items':it},
        success:function(data){
            let oid = parseInt(data)+Math.round(Math.random()*(9999-1000)+1000)
            url = 'http://sachtechsolution.pe.hu/easypayment/payment.php?mid=JFeXSP79054240666398&amount='+amount+'&adminemail=akd6203@gmail.com&adminmobile=9779945093&mkey=yrE%23_4HmnGqs%25PFo&orderid='+data+'o'+oid+'&returnurl=http://127.0.0.1:8000{% url "myapp:success_payment" %}';
            window.location = url; 
        }
    })
    
})
</script>
{% else %}
<h1 class="p-5 m-5">To View Cart, You need to Login First!!</h1>
{% endif %}
{% endblock %}

templates/dashboard.html
{% extends "base.html"%}
{% load staticfiles%}
{% block style %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
<link rel="stylesheet" href="{% static 'mystyle.css'%}">

{% endblock %}
{% block body %}
<div class='container-fluid'>
    <div class='row'>
        <div class='col-md-3'>
            {% if user.is_authenticated %}
            <div class='ab pt-2'>
                <img src="/media/{{pp.profile_pic}}" class='dash-img' style='height:80px;width:80px;border-radius: 50%;'>
                <p><a href="{% url 'myapp:profile'%}"> {{pp.subtitle}} {{user.first_name}}</a></p>
            </div>
            <div class='ab list-group'>
                <h4 class='title'><i class="far fa-address-card"></i> Manage Profile</h4>
                <a href="{% url 'myapp:profile'%}" class='list-group-item dash'>My Profile</a>
                <a href="{% url 'myapp:change_profile' %}" class='list-group-item dash'>Change Profile</a>
                <a href="{% url 'myapp:change_password' %}" class='list-group-item dash'>Change Password</a>
            </div>
            <div class='ab'>
                <h4 class='title'><i class="fas fa-cart-arrow-down"></i> My Orders</h4>
                <a href="{% url 'myapp:orders'%}" class='list-group-item dash'>Order History</a>
                <a href="{% url 'myapp:pending_orders'%}" class='list-group-item dash'>Pending Orders</a>     
            </div>
            <div class='ab'>
                <h4 class='title'>
                    <a href="{% url 'uslogout'%}" class='list-group-item dash'><i class="fas fa-sign-out-alt"></i> Logout</a>
                </h4>
            </div>
            {% endif %}
        </div>
        <div class='col-md-9' id='rcover'>
            {% block content %}
            {% endblock %}
        </div>
    </div>
</div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body %}
{% if response %}
<script>
    alert('{{response}}');
</script>
{% endif %}
	<!-- banner -->
	<div class="banner">
		<div class="container">
			<h3>Electronic Store, <span>Special Offers</span></h3>
		</div>
	</div>
	<!-- //banner --> 
	<!-- banner-bottom -->
	<div class="banner-bottom">
		<div class="container">
			<div class="col-md-5 wthree_banner_bottom_left">
				<div class="video-img">
					<a class="play-icon popup-with-zoom-anim" href="#small-dialog">
						<span class="glyphicon glyphicon-expand" aria-hidden="true"></span>
					</a>
				</div> 
					<!-- pop-up-box -->     
					<script src="{% static 'js/jquery.magnific-popup.js'%}" type="text/javascript"></script>
					<!--//pop-up-box -->
					<div id="small-dialog" class="mfp-hide">
						<iframe src="https://www.youtube.com/embed/ZQa6GUVnbNM"></iframe>
					</div>
					<script>
						$(document).ready(function() {
							$('#Cameras-tab').click();
						$('.popup-with-zoom-anim').magnificPopup({
							type: 'inline',
							fixedContentPos: false,
							fixedBgPos: true,
							overflowY: 'auto',
							closeBtnInside: true,
							preloader: false,
							midClick: true,
							removalDelay: 300,
							mainClass: 'my-mfp-zoom-in'
						});
						
																						
						});				
					</script>
			</div>
			<div class="col-md-7 wthree_banner_bottom_right">
				<div class="bs-example bs-example-tabs" role="tabpanel" data-example-id="togglable-tabs">
					<ul id="myTab" class="nav nav-tabs" role="tablist">
						{% for i in cat %}
						<li role="presentation" class='{% if i.id is 2%}active{% endif %}'><a href="#{{i.category_name}}" id="{{i.category_name}}-tab" role="tab" data-toggle="tab" aria-controls="{{i.category_name}}" onclick ="getproduct('{{i.category_name}}')">{{i.category_name}}</a></li>
						{% endfor %}
					</ul>
					<script>
						function myfun(e){
							prid = e;
							$.ajax({
								url:'{% url "index" %}',
								type:'get',
								data:{prid:prid},
								success:function(data){
									var check = (data.description).search('@');
									if(check==-1){
										dsc = data.description;
									}
									else{
										var dd = (data.description).split('@');
										dsc = '';
										for(var i=0; i<dd.length-1;i++){
											dsc+='<li>'+dd[i]+'</li>';
										}
									}
									$('.pimg').html('<img src="/media/'+data.photo+'" alt="No Image" class="img-responsive" height="100%"/>');
									$('#pname').html(data.name);
									$('#pdes').html('<ul>'+dsc+'</ul>');
									$('#pp').html(data.price);
									$('#sp').html(data.sale_price); 
									$('#iprice').val(data.sale_price);
									$('#item_id').val(data.id);
								}
							});
						}
					</script>
					<script>
						function getproduct(ab){
								$.ajax({
									url:'{% url "index"%}',
									type:'get',
									data:{cat:ab},
									success:function(data){
										aa='';
										for(i in data){
											aa += '<div class="col-md-4 agile_ecommerce_tab_left"><div class="hs-wrapper"><img src="media/'+data[i].photo+'" alt=" " class="img-responsive" style="height:100%;width:100%;"/><img src="media/'+data[i].photo+'" alt=" " class="img-responsive" style="height:100%;width:100%;"/><img src="media/'+data[i].photo+'" alt=" " class="img-responsive" style="height:100%;width:100%;"/><img src="media/'+data[i].photo+'" alt=" " class="img-responsive" style="height:100%;width:100%;"/><img src="media/'+data[i].photo+'" alt=" " class="img-responsive" style="height:100%;width:100%;"/><div class="w3_hs_bottom"><ul><li><a href="#" onclick="myfun('+data[i].id+')" data-toggle="modal" data-target="#myModal"><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span></a></li></ul></div></div><h5 style="height:80px;"><a href="{% url "myapp:singleproduct" %}?singlep='+data[i].id+'">'+data[i].product_name+'</a></h5><div class="simpleCart_shelfItem"><p><span>&#8377;'+data[i].price+'</span> <i class="item_price">&#8377;'+data[i].sale_price+'</i></p><form action="{% url "myapp:cart"%}" method="post">{% csrf_token %}<input type="hidden" name="add" value="1" /><input type="hidden" name="item_id" value="'+data[i].id+'" /><input type="hidden" name="amount" value="'+data[i].sale_price+'" /><button type="submit" class="w3ls-cart">Add to cart</button></form></div></div>';
										}
										$('.agile_ecommerce_tabs').html(aa);
									}
								});
							}
					</script>
					<div id="myTabContent" cla
					0ss="tab-content">
						
						<div role="tabpanel" class="tab-pane fade active in" id="{{i.category_name}}" aria-labelledby="{{i.category_name}}-tab" >
							<div class="agile_ecommerce_tabs">					
								<div class="clearfix"> </div>
							</div>
						</div>
						<!-- END REPEAT CODE		 -->
					</div>
				</div> 
			</div>
			<div class="clearfix"> </div>
		</div>
	</div>
	<!-- //banner-bottom --> 
	<!-- modal-video -->
	<div class="modal video-modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModal">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>						
				</div>
				<section>
					<div class="modal-body">
						<div class="col-md-5 modal_body_left pimg">

						</div>
						<div class="col-md-7 modal_body_right">
							<h4 id='pname'></h4>
							<p id='pdes'></p>
							<div class="rating">
								<div class="rating-left">
									<img src="{% static 'images/star-.png'%}" alt=" " class="img-responsive" />
								</div>
								<div class="rating-left">
									<img src="{% static 'images/star-.png'%}" alt=" " class="img-responsive" />
								</div>
								<div class="rating-left">
									<img src="{% static 'images/star-.png'%}" alt=" " class="img-responsive" />
								</div>
								<div class="rating-left">
									<img src="{% static 'images/star.png'%}" alt=" " class="img-responsive" />
								</div> 
								<div class="rating-left">
									<img src="{% static 'images/star.png'%}" alt=" " class="img-responsive" />
								</div>
								<div class="clearfix"> </div>
							</div>
							<div class="modal_body_right_cart simpleCart_shelfItem">
								<p>&#8377;<span id='pp'></span> <i class="item_price" id='sp'></i></p>
								<form action='{% url "myapp:cart"%}' method="post">
									{% csrf_token %}
									<input type="hidden" name='item_id' id='item_id'>
									<input type="hidden" name="w3ls_item" value="" id='pn'> 
									<input type="hidden" name="amount" id='iprice' value="">   
									<input type="hidden" name="add" value="1">   
									<button type="submit" class="w3ls-cart">Add to cart</button>
								</form>
							</div>
							<h5>Color</h5>
							<div class="color-quality">
								<ul>
									<li><a href="#"><span></span></a></li>
									<li><a href="#" class="brown"><span></span></a></li>
									<li><a href="#" class="purple"><span></span></a></li>
									<li><a href="#" class="gray"><span></span></a></li>
								</ul>
							</div>
						</div>
						<div class="clearfix"> </div>
					</div>
				</section>
			</div>
		</div>
	</div>
	
	<!-- //modal-video -->
	<!-- banner-bottom1 -->
	<div class="banner-bottom1">
		<div class="agileinfo_banner_bottom1_grids">
			<div class="col-md-7 agileinfo_banner_bottom1_grid_left">
				<h3>Grand Opening Event With flat<span>20% <i>Discount</i></span></h3>
				<a href="products.html">Shop Now</a>
			</div>
			<div class="col-md-5 agileinfo_banner_bottom1_grid_right">
				<h4>hot deal</h4>
				<div class="timer_wrap">
					<div id="counter"> </div>
				</div>
				<script src="{% static 'js/jquery.countdown.js'%}"></script>
				<script src="{% static 'js/script.js'%}"></script>
			</div>
			<div class="clearfix"> </div>
		</div>
	</div>
	<!-- //banner-bottom1 --> 
	<!-- special-deals -->
	<div class="special-deals">
		<div class="container">
			<h2>Special Deals</h2>
			<div class="w3agile_special_deals_grids">
				<div class="col-md-7 w3agile_special_deals_grid_left">
					<div class="w3agile_special_deals_grid_left_grid">
						<img src="{% static 'images/21.jpg' %}" alt=" " class="img-responsive" />
						<div class="w3agile_special_deals_grid_left_grid_pos1">
							<h5>{{to}}%<span>Off/-</span></h5>
						</div>
						<div class="w3agile_special_deals_grid_left_grid_pos">
							<h4>We Offer <span>Best Products</span></h4>
						</div>
					</div>
					<div class="wmuSlider example1">
						<div class="wmuSliderWrapper">
							<article style="position: absolute; width: 100%; opacity: 0;"> 
								<div class="banner-wrap">
									<div class="w3agile_special_deals_grid_left_grid1">
										<img src="{% static 'images/t1.png' %}" alt=" " class="img-responsive" />
										<p>People generally choose this place to buy clothes in a limited budget.Everyone must try!!!</p>
										<h4>Jenny</h4>
									</div>
								</div>
							</article>
							<article style="position: absolute; width: 100%; opacity: 0;"> 
								<div class="banner-wrap">
									<div class="w3agile_special_deals_grid_left_grid1">
										<img src="{% static 'images/t2.png' %}" alt=" " class="img-responsive" />
										<p>Electronic gadgets & all items are good for quality and price. I recommend to all my friends to visit the site and get quality products.</p>
										<h4>Robert</h4>
									</div>
								</div>
							</article>
							<article style="position: absolu0te; width: 100%; opacity: 0;"> 
								<div class="banner-wrap">
									<div class="w3agile_special_deals_grid_left_grid1">
										<img src="{% static 'images/t3.png'%}" alt=" " class="img-responsive" />
										<p>I just love the site. All products are very good in quality and also good price. Thanks to make my life easy and styled!!!</p>
										<h4>Rosy</h4>
									</div>
								</div>
							</article>
						</div>
					</div>
						<script src="{% static 'js/jquery.wmuSlider.js' %}"></script> 
						<script>
							$('.example1').wmuSlider();         
						</script> 
				</div>
				<div class="col-md-5 w3agile_special_deals_grid_right">
					<img src="/media/{{eimg}}" alt="No Image" style='height:600px; opacity:0.9;' class="img-responsive" />
					<div class="w3agile_special_deals_grid_right_pos">
						<h4>{{epnm}} <span>Special</span></h4>
						<h5>save up <span>to</span> {{eoff}}%</h5>
					</div>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
	<!-- //special-deals -->
	<!-- new-products -->
	<div class="new-products">
		<div class="container">
			<h3>New Products</h3>
			<div class="agileinfo_new_products_grids">
				{% for x in lp %}
				<div class="col-md-3 agileinfo_new_products_grid">
						<div class="agile_ecommerce_tab_left agileinfo_new_products_grid1">
							<div class="hs-wrapper hs-wrapper1">
								<img src="/media/{{x.photo}}" alt=" " style='height:90%; width:100%' class="img-responsive" />
								<img src="/media/{{x.photo}}" alt=" " style='height:90%; width:100%' class="img-responsive" />
								<img src="/media/{{x.photo}}" alt=" " style='height:90%; width:100%' class="img-responsive" />
								<img src="/media/{{x.photo}}" alt=" " style='height:90%; width:100%' class="img-responsive" />
								<img src="/media/{{x.photo}}" alt=" " style='height:90%; width:100%' class="img-responsive" /> 
								<div class="w3_hs_bottom w3_hs_bottom_sub">
									<ul>
										<li>
											<a href="#" data-toggle="modal" data-target="#myModal" onclick="myfun('{{x.id}}')"><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span></a>
										</li>
									</ul>
								</div>
							</div>
							<h5><a href="{% url 'myapp:singleproduct'%}?singlep={{x.id}}">{{x.product_name}}</a></h5>
							<div class="simpleCart_shelfItem">
								<p><span>&#8377;{{x.price}}</span> <i class="item_price">&#8377; {{x.sale_price}}</i></p>
								<form action="{% url 'myapp:cart' %}" method="post">
									{% csrf_token %}
									<input type="hidden" name="add" value="1"> 
									<input type="hidden" name="w3ls_item" value="{{x.product_name}}"> 
									<input type="hidden" name="amount" value="{{x.sale_price}}">   
									<input type="hidden" name="item_id" value="{{x.id}}">   
									<button type="submit" class="w3ls-cart">Add to cart</button>
								</form>
							</div>
						</div>
					</div>
				{% endfor %}
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
	<!-- //new-products -->
	<!-- top-brands -->
	<div class="top-brands">
		<div class="container">
			<h3>Top Brands</h3>
			<div class="sliderfig">
				<ul id="flexiselDemo1">					
					{% for i in brands %}
					<li>
						<img src="/media/{{i.brand_logo}}" alt=" " style='height:100px' class="img-responsive" style='display:inline;'/>
					</li>
					{% endfor %}
					
				</ul>
			</div>
			<script type="text/javascript">
					$(window).load(function() {
						$("#flexiselDemo1").flexisel({
							visibleItems: 4,
							animationSpeed: 1000,
							autoPlay: true,
							autoPlaySpeed: 3000,    		
							pauseOnHover: true,
							enableResponsiveBreakpoints: true,
							responsiveBreakpoints: { 
								portrait: { 
									changePoint:480,
									visibleItems: 1
								}, 
								landscape: { 
									changePoint:640,
									visibleItems:2
								},
								tablet: { 
									changePoint:768,
									visibleItems: 3
								}
							}
						}); 
						
					});
			</script>
			<script type="text/javascript" src="{% static 'js/jquery.flexisel.js'%}"></script>
		</div>
	</div>
	<!-- //top-brands -->
{% endblock %}

templates/pending.html
{% extends "dashboard.html" %}
{% load staticfiles%}
{% block style %}
<link rel="stylesheet" href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
<script src='//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js'></script>
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
<link rel="stylesheet" href="{% static 'mystyle.css'%}">
<style>
.ab{
    border:1px solid black !important;
}
</style>
{% endblock %}
{% block content %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
    <h2 class='py-5'>Pending Orders</h2>
    <table class='table table-striped table-hover table-bordered' id='myTable'>
        <thead>
            <tr>
                <th>Order ID</th>
                <th>Total Price</th>
                <th>Received On</th>
                <th>Processed On</th>
                <th>View Items</th>
            </tr>
        </thead>
        <tbody>
            {% for i in pending_orders %}
                <tr>
                    <td>{{i.id}}</td>
                    <td>{{i.amount}}</td>
                    <td>{{i.received_on}}</td>
                    <td>{{i.changed_on}}</td>
                    <td>
                        <a href="{% url 'myapp:order_detail'%}?id={{i.id}}"><button id='' class='btn btn-sm btn-primary'>View</button></a>
                    </td>

                </tr>
            {% endfor %}
        </tbody>
    </table>
    <script>
    $(function(){
        $('#myTable').DataTable();
    })
    </script>
{% endblock %}